
<option value='PRO'>PRO</option>
<option value='CRO'>CRO</option>
<option value='SRO'>SRO</option>
<option value='ROI'>ROI</option>
<option value='ROII'>ROII</option>
<option value='ROIII'>ROIII</option>
<option value='SCO'>SCO</option>
<option value='COI'>COI</option>
<option value='COII'>COII</option>
<option value='DRIVER I'>DRIVER I</option>
<option value='DRIVER II'>DRIVER II</option>
<option value='DRIVER III'>DRIVER III</option>
<option value='SCH'>SCH</option>
<option value='OAA I'>OAAA I</option>
<option value='OAA II'>OAAA II</option>
<option value='OAA III'>OAAA III</option>
<option value='SSS'>SSS</option>
<option value='SS'>SS</option>
<option value='F.O.III'>F.O.III</option>
<option value='F.O.II'>F.O.II</option>
<option value='F.O.I'>F.O.I</option>
<option value='CSIIB'>CSIIB</option>
<option value='SCH'>SCH</option>
<option value='CS1'>CS1</option>
<option value='SNR SEC'>SNR SEC</option>
<option value='SEC ASST I'>SEC ASST I</option>
<option value='CSIIA'>CSIIA</option>
<option value='PSI'>PSI</option>
<option value='CSIA'>CSIA</option>
</select>