<?PHP echo"<option value=''></option>
<option value='NAKURU'>NAKURU</option>
<option value='HDM NAKURU'>HDM NAKURU</option>
<option value='NAKURU NORTH'>NAKURU NORTH</option>
<option value='NAKURU WEST'>NAKURU WEST</option>
<option value='NJORO'>NJORO</option>
<option value='SUBUKIA'>SUBUKIA</option>
<option value='NAIVASHA'>NAIVASHA</option>
<option value='MOLO'>MOLO</option>
<option value='KURESOI SOUTH'>KURESOI SOUTH</option>
<option value='KURESOI NORTH'>KURESOI NORTH</option>
<option value='RONGAI'>RONGAI</option>
<option value='GILGIL'>GILGIL</option>
<option value='NAKURU HDM'>NAKURU HDM</option>
<option value='BARINGO CENTRAL'>BARINGO CENTRAL</option>
<option value='HDM BARINGO'>HDM BARINGO</option>
<option value='BARINGO NORTH'>BARINGO NORTH</option>
<option value='MOGOTIO'>MOGOTIO</option>
<option value='MARIGAT'>MARIGAT</option>
<option value='EAST POKOT'>EAST POKOT</option>
<option value='KOIBATEK'>KOIBATEK</option>
<option value='NAROK NORTH'>NAROK NORTH</option>
<option value='HDM NAROK'>HDM NAROK</option>
<option value='NAROK SOUTH'>NAROK SOUTH</option>
<option value='TRANSMARA EAST'>TRANSMARA EAST</option>
<option value='TRANSMARA WEST'>TRANSMARA WEST</option>
<option value='SAMBURU CEN'>SAMBURU CEN</option>
<option value='HDM SAMBURU'>HDM SAMBURU</option>
<option value='SAMBURU N'>SAMBURU N</option>
<option value='SAMBURU E'>SAMBURU E</option>
<option value='KERICHO EAST'>KERICHO EAST</option>
<option value='KERICHO WEST'>KERICHO WEST</option>
<option value='HDM KERICHO'>HDM KERICHO</option>
<option value='BURETI'>BURETI</option>
<option value='LONDIANI'>LONDIANI</option>
<option value='SOIN SIGOWET'>SOIN SIGOWET</option>
<option value='KIPKELION'>KIPKELION</option>
<option value='LAIKIPIA E'>LAIKIPIA E</option>
<option value='LAIKIPIA N'>LAIKIPIA N</option>
<option value='NYAHURURU'>NYAHURURU</option>
<option value='LAIKIPIA W'>LAIKIPIA W</option>
<option value='LAIKIPIA C'>LAIKIPIA C</option>
<option value='HDM LAIKIPIA'>HDM LAIKIPIA</option>
<option value='BOMET CENTRAL'>BOMET CENTRAL</option>
<option value='HDM BOMET'>HDM BOMET</option>
<option value='BOMET EAST'>BOMET EAST</option>
<option value='CHEPALUNGU'>CHEPALUNGU</option>
<option value='KONOIN'>KONOIN</option>
<option value='SOTIK'>SOTIK</option>";
?>